/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fauzan Maulana Alfany
 */
public class FormBerat extends javax.swing.JFrame {

    /**
     * Creates new form FormBerat
     */
    public FormBerat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNAMA = new javax.swing.JTextField();
        txtBERAT = new javax.swing.JTextField();
        txtTINGGI = new javax.swing.JTextField();
        txtNIM = new javax.swing.JTextField();
        Cek1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Cek2 = new javax.swing.JButton();
        HSL = new javax.swing.JLabel();
        J = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NAMA");

        jLabel2.setText("NIM");

        jLabel3.setText("BERAT");

        jLabel4.setText("TINGGI");

        Cek1.setText("WHO (BMI)");
        Cek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cek1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Berdasarkan:");

        Cek2.setText("Asia-Pacific (BMI)");
        Cek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cek2ActionPerformed(evt);
            }
        });

        HSL.setText("Hasil");

        J.setText("KG");

        jLabel6.setText("CM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HSL)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNAMA, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addComponent(txtNIM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtBERAT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTINGGI, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cek1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Cek2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(J))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)))))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBERAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTINGGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cek1)
                    .addComponent(jLabel5)
                    .addComponent(Cek2))
                .addGap(26, 26, 26)
                .addComponent(HSL)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Cek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cek1ActionPerformed
        // TODO add your handling code here:
        
        if (txtBERAT.getText().trim().isEmpty() & txtTINGGI.getText().trim().isEmpty()){
            HSL.setText("Mohon lengkapi data");
        }else{ 
            String s1 = txtBERAT.getText();  
            String s2 = txtTINGGI.getText();
            double a = Double.parseDouble(s1);  
            double b = Double.parseDouble(s2);  
            double c = 0,d = 0;
            d = (b*b/10000);
            c = a/d;
            if(c<18.5){
                String result = String.valueOf(String.format("%.2f",c));
                HSL.setText("Dengan hasil: "+result+" kamu termasuk Kurus");
            }else if(c>=18.5 & c<=24.9){  
                String result = String.valueOf(String.format("%.2f",c));
                HSL.setText("Dengan hasil: "+result+" kamu termasuk Normal");  
            }else if(c>=25 & c<=29.9){  
                String result = String.valueOf(String.format("%.2f",c));
                HSL.setText("Dengan hasil: "+result+" kamu termasuk Overweight");
            }else{
                String result = String.valueOf(String.format("%.2f",c));
                HSL.setText("Dengan hasil: "+result+" kamu termasuk Obesitas");
            }
        }
    }//GEN-LAST:event_Cek1ActionPerformed

    private void Cek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cek2ActionPerformed
        // TODO add your handling code here:
        if (txtBERAT.getText().trim().isEmpty() & txtTINGGI.getText().trim().isEmpty()){
            HSL.setText("Mohon lengkapi data");
        }else{ 
            String s1 = txtBERAT.getText();  
            String s2 = txtTINGGI.getText();
            double a = Double.parseDouble(s1);  
            double b = Double.parseDouble(s2);  
            double c = 0,d = 0;
            d = (b*b/10000);
            c = a/d;
            if(c<18.5){
                String result = String.valueOf(String.format("%.2f",c));
                HSL.setText("Dengan hasil: "+result+" kamu termasuk Kurus");
            }else if(c>=18.5 & c<=22.9){  
                String result = String.valueOf(String.format("%.2f",c));
                HSL.setText("Dengan hasil: "+result+" kamu termasuk Normal");  
            }else if(c>=23 & c<=24.9){  
                String result = String.valueOf(String.format("%.2f",c));
                HSL.setText("Dengan hasil: "+result+" kamu termasuk Overweight");
            }else{
                String result = String.valueOf(String.format("%.2f",c));
                HSL.setText("Dengan hasil: "+result+" kamu termasuk Obesitas");
            }
        }
    }//GEN-LAST:event_Cek2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBerat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBerat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBerat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBerat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBerat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cek1;
    private javax.swing.JButton Cek2;
    private javax.swing.JLabel HSL;
    private javax.swing.JLabel J;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtBERAT;
    private javax.swing.JTextField txtNAMA;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtTINGGI;
    // End of variables declaration//GEN-END:variables
}
